PEDSnet/pedsnetcdm_to_pcornetcdm

ETL Scripts/PEDSnet-PCORnet.sql

added left join

---

v2 to v3/ETL Scripts/PEDSnetV2-PCORnetV3.sql
v2 to v3/pedsnet_pcornet_mappings.txt

addressing issue-7

---

v2 to v3/ETL Scripts/Dispensing_ETL.sql

For @toanong to review 
#22 and #23 still pending.

adding dispensing query

---

v2 to v3/ETL Scripts/Dispensing_ETL.sql

adding pk to etl - issue 22

---

v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql

addressing issue 39

---

v2 to v3/ETL Scripts/Death_Cause_ETL.sql

addressing #28

---

v2 to v3/ETL Scripts/Death_ETL.sql

fixes to death etl

---

v2 to v3/ETL Scripts/Prescribing_ETL.sql

fixes to prescribing query

---

v2 to v3/ETL Scripts/Vital_ETL.sql

adding person_id to the concatenated vital PK

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_Cause_ETL.sql
v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Dispensing_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/Prescribing_ETL.sql
v2 to v3/ETL Scripts/Vital_ETL.sql

addressing #65 - adding comments

---

v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql

temp fix for issue 77

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_Cause_ETL.sql
v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Demographic_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql
v2 to v3/ETL Scripts/Dispensing_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Enrollment_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/PRO_CM_ETL.sql
v2 to v3/ETL Scripts/Prescribing_ETL.sql
v2 to v3/ETL Scripts/Procedure_ETL.sql
v2 to v3/ETL Scripts/Vital_ETL.sql
v2 to v3/ETL Scripts/cz_omop_pcornet_concept_map_ddl.sql
v2 to v3/README.md

updating schema name and fixing pxsource

---

v2 to v3/ETL Scripts/Diagnosis_ETL.sql

addressing issue 91 diagnosis

---

v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql

fixes #95
Thanks @baileych for finding this bug

removing vitals from labs

---

v2 to v3/ETL Scripts/Death_Cause_ETL.sql

fixing cause vocab bug

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_Cause_ETL.sql
v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Demographic_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql
v2 to v3/ETL Scripts/Dispensing_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Enrollment_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/Prescribing_ETL.sql
v2 to v3/ETL Scripts/Procedure_ETL.sql
v2 to v3/ETL Scripts/Vital_ETL.sql
v2 to v3/README.md

adding siteid to transform scripts and table defs

---

v2 to v3/ETL Scripts/Dispensing_ETL.sql

fixing the bug in dispensing

---

v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Demographic_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/PRO_CM_ETL.sql
v2 to v3/ETL Scripts/Prescribing_ETL.sql
v2 to v3/ETL Scripts/Procedure_ETL.sql
v2 to v3/ETL Scripts/Vital_ETL.sql
v2 to v3/ETL Scripts/cz_omop_pcornet_concept_map_ddl.sql
v2 to v3/README.md

replace public with dcc_pcornet schema

---

v2 to v3/ETL Scripts/Death_ETL.sql

selecting one death record in case of multiple causes

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_Cause_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql
v2 to v3/ETL Scripts/Dispensing_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Procedure_ETL.sql

Issue 110 dispensing bug

---

v2 to v3/FK_statements.sql
v2 to v3/README.md
v2 to v3/index_statements.sql

fixes #108  
FKs have been created on test server, and getting no disk space error when creating some indexes.

adding FK and indexes

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_Cause_ETL.sql
v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Demographic_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql
v2 to v3/ETL Scripts/Dispensing_ETL.sql
v2 to v3/ETL Scripts/Encounter_ETL.sql
v2 to v3/ETL Scripts/Enrollment_ETL.sql
v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/Prescribing_ETL.sql
v2 to v3/ETL Scripts/Procedure_ETL.sql
v2 to v3/ETL Scripts/Vital_ETL.sql
v2 to v3/README.md

adding site column and dropping siteid

---

v2 to v3/ETL Scripts/Condition_ETL.sql
v2 to v3/ETL Scripts/Death_ETL.sql
v2 to v3/ETL Scripts/Diagnosis_ETL.sql

reordering vocabularies

---

v2 to v3/ETL Scripts/Dispensing_ETL.sql

See https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/issues/118

Issue 118 ndc constraint

---

v2 to v3/ETL Scripts/start2001/ETL Scripts/chop/Dispensing_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Dispensing_ETL.sql

Harris made changes to  where clause                    for NDC
selection.

updated to include Harris' changes

---

v2 to v3/ETL Scripts/Lab_Result_CM_ETL.sql

fixing issue 119

---

v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Condition_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Dispensing_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Lab_Result_CM_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Prescribing_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Procedure_ETL.sql
v2 to v3/ETL Scripts/start2001/ETL Scripts/dcc/Vital_ETL.sql

fixes #146 
@writetoritu please review

adding filter statements in individual files

---

v2 to v3.1/ETL Scripts/Lab_Result_CM_ETL.sql

including all labs

---

v2 to v3.1/ETL Scripts/Prescribing_ETL.sql
v2 to v3.1/ETL Scripts/start2001/Prescribing_ETL.sql

addressing issue-164

---

v2 to v3.1/ETL Scripts/start2001/Condition_ETL.sql
v2 to v3.1/ETL Scripts/start2001/FK_statements.sql
v2 to v3.1/ETL Scripts/start2001/Prescribing_ETL.sql
v2 to v3.1/ETL Scripts/start2001/Procedure_ETL.sql
v2 to v3.1/ETL Scripts/start2001/index_statements.sql

edits to fix issue fk  violations

---

v2.5_to_v3.1/README.md
v2.5_to_v3.1/cz_omop_pcornet_concept_map_ddl.sql

fixing 162

---

v2.5_to_v3.1/ETL Scripts/Condition_ETL.sql

icd->snomed->ot

---

v2.5_to_v3.1/ETL Scripts/Demographic_ETL.sql

correct patid typo

---

v2.5_to_v3.1/ETL Scripts/Death_ETL.sql

drop redundant join to person table

---

v2.5_to_v3.1/ETL Scripts/Encounter_ETL.sql

dropping constraints for AV and OA visits only

---

v2.5_to_v3.1/ETL Scripts/Lab_Result_CM_ETL.sql

making lab_loinc as null for no matching concepts

---

loading/concept_map_csv/concept_map.csv
loading/config.py
loading/database_sample.ini
loading/sql.py
pcornet_loading/.gitignore
pcornet_loading/.idea/dbnavigator.xml
pcornet_loading/.idea/misc.xml
pcornet_loading/.idea/modules.xml
pcornet_loading/.idea/pcornet_loading.iml
pcornet_loading/.idea/workspace.xml
pcornet_loading/README.MD
pcornet_loading/concept_map/concept_map.csv
pcornet_loading/config.py
pcornet_loading/database_sample.ini
pcornet_loading/loading/main.py
pcornet_loading/loading/query.py
pcornet_loading/requirements.txt
pcornet_loading/scripts/create_table.sql
pcornet_loading/setup.py

Concept Map in text are converted into CSV. Concept maps will be
directly uploaded into the database using this script.

Concept Map Loading Script

---

v2.6_to_3.1/ETL Scripts/Demographic_ETL.sql

The Mapping table name changes are modified in the script. It was changed to 
'  pedsnet_pcornet_valueset_map ' 
The time_of_birth column name changed to 
' birth_datetime '

Modified the references

---

v2.6_to_3.1/ETL Scripts/Death_ETL.sql

pedsnet-to-pcornet mapping table name changed from
'cz_omop_pcornet_concept_map'                  to
'pedsnet_pcornet_valueset_map'

modified the reference to the mapping table

---

v2.6_to_3.1/ETL Scripts/Death_Cause_ETL.sql

Modified the name of mapping table

---

v2.6_to_3.1/ETL Scripts/Encounter_ETL.sql

#PROGPEDS-31   Jira issue
@writetoritu 
Following error received:
_**ERROR: column "visit_start_time" does not exist LINE 26: date_part('hour',visit_start_time)||':'||date_part('minu...
HINT: Perhaps you meant to reference the column "v.visit_start_date". Query returned successfully in 203 sec.**_
The column name in the visit_start_time not present in stlouis_pcornet the column visit_start_datetime. Following modification were made in script:
1.  the reference column from visit_occurrence in the query was changed from
**visit_start_time**                 to                **visit_start_datetime**
2. The reference to concept map was changed
**cz_omop_pedsnet_pcornet_map**                   to                   **pedsnet_pcornet_valueset_map**

Col name visit_start_time & concept map update

---

v2.6_to_3.1/ETL Scripts/Diagnosis_ETL.sql

cz_omop_pedsnet_pcornet_map changed to  pedsnet_pcornet_valueset_map

Mapping file reference changed

---

v2.6_to_3.1/ETL Scripts/Dispensing_ETL.sql

The script had 
`delete from stlouis_pedsnet_3dot1_pcornet.dispensing`
giving ERROR while running script
```
ERROR:  syntax error at or near "into"
LINE 5: insert into stlouis_pedsnet_3dot1_pcornet.dispensing(
^
********** Error **********
ERROR: syntax error at or near "into"
SQL state: 42601
Character: 220
```

removed 'delete from stlouis_pedsnet... '

---

v2.6_to_3.1/ETL Scripts/Vital_ETL.sql

following changes were made:
`cz_omop_pcornet_concept_map`  to `pedsnet_pcornet_valueset_map`
and 
`measurement_time` from measurement table has no column named the same. so the script was modified to `measurement_datetime` 
```
ERROR:  column "measurement_time" does not exist
LINE 23: ...te) as site,visit_occurrence_id,measurement_date, measuremen...
^
HINT:  Perhaps you meant to reference the column "measurement.measurement_date" or the column "measurement.measurement_id".
********** Error **********
ERROR: column "measurement_time" does not exist
SQL state: 42703
Hint: Perhaps you meant to reference the column "measurement.measurement_date" or the column "measurement.measurement_id".
Character: 1090
```

measurement_datetime updated

---

v2.6_to_3.1/transform_map/concept_map/concept_map.csv

fixes #258 
following things were modified
- add header name
- update map for 'admitting source' , replace source_concept_id with value_as_concept_id and default value_as_concept_id to NULL
- drop lines 37-55
- update map for 'discharge status' , replace source_concept_id with value_as_concept_id and default value_as_concept_id to NULL

updates concept_map.csv

---

v2.6_to_3.1/ETL Scripts/Encounter_ETL.sql

fixes #256
The script was modified to accommodate the changes in the PEDSnet CDM2.6

Encounter script modified for PEDSnet CDM2.6

---

v2.6_to_3.1/ETL Scripts/Diagnosis_ETL.sql

fixes #215
diagnosis query, replaced 
`case when enc_type in ('IP','IS') `
with
`case when enc_type in ('IP','IS','OS')`

updated diagnosis script to add 'OS'

---

v2.6_to_3.1/ETL Scripts/Encounter_ETL.sql

Revised Encounter script

---

v2.6_to_3.1/ETL Scripts/Lab_Result_CM_ETL.sql
v2.6_to_3.1/transform_map/concept_map/concept_map.csv

adding logic for result qualifier

---

v2.6_to_3.1/transform_map/concept_map/concept_map.csv

The missing lab codes from V2.5 missing causing errors in the lab tables were added in the file.

added the missing lab codes

---

v2.6_to_3.1/Reset_tables_script/trunc_fk_idx.sql

The raise info statements giving error, so removed from the code.

Truncating table script modified.

---

v2.7_to_3.1/ETL Scripts/Encounter_ETL.sql
v2.7_to_3.1/ETL Scripts/Lab_Result_CM_ETL.sql
v2.7_to_3.1/ETL Scripts/Vital_ETL.sql

refactor lab , encounter and vital queries

---

v2.7_to_3.1/ETL Scripts/Encounter_ETL.sql

correcting the DRG logic

---

v2.7_to_3.1/pcornet_loading/scripts/etl_scripts/a_demographic.sql

adding leading 0s in birthtime field

---

v2.7_to_3.1/sql_etl/scripts/etl_scripts/u_start2001_diagnosis.sql

added missing column

---

v2.7_to_3.1/sql_etl/data/concept_map.csv
v2.7_to_3.1/sql_etl/scripts/etl_scripts/g_procedure.sql

adding px source mapping and edits to scripts

---

v2.7_to_3.1/python_etl/.idea/dbnavigator.xml
v2.7_to_3.1/python_etl/.idea/misc.xml
v2.7_to_3.1/python_etl/.idea/modules.xml
v2.7_to_3.1/python_etl/.idea/python_etl.iml
v2.7_to_3.1/python_etl/.idea/workspace.xml
v2.7_to_3.1/python_etl/demographicsETL.py
v2.7_to_3.1/python_etl/enrollment.py
v2.7_to_3.1/python_etl/enrollmentETL.py
v2.7_to_3.1/python_etl/workflow.py

Python ETL updated to include the ETL for Enrollment table

pythonETL upgraded - Enrollment

---

v2.7_to_3.1/sql_etl/scripts/etl_scripts/e_encounter.sql
v2.7_to_3.1/sql_etl/scripts/etl_scripts/j_vital.sql
v2.7_to_3.1/sql_etl/scripts/etl_scripts/k_lab_result_cm.sql

restoring the changes due to refactoring of queries

---

v2.7_to_3.1/README.md
v2.7_to_3.1/sql_etl/README.md
v2.7_to_3.1/sql_etl/loading/main.py

fixes#364
Read me was modified to correct the directory and file path.
Harvest table date refresh feature added not tested yet.

correct the directory paths/names in documentation for sql-etl tool

---

v2.8_to_3.1/sql_etl/scripts/etl_scripts/f_encounter.sql
v2.8_to_3.1/sql_etl/scripts/etl_scripts/l_vitals.sql

refactoring and optimizing encounter and vital queries

---

README.md
v2.8_to_3.1/README.md
v2.8_to_3.1/sql_etl/README.md
v2.8_to_3.1/sql_etl/bash_script/etl_bash.sh
v2.8_to_3.1/sql_etl/scripts/ddl_scripts/create_table.sql

updated readme and resolved few tasks from issue 374

updated readME issue 374

---

v2.8_to_v4.0/sql_etl/scripts/etl_scripts/a_person_visit_start2001.sql
v2.8_to_v4.0/sql_etl/scripts/etl_scripts/c_enrollment.sql
v2.8_to_v4.0/sql_etl/scripts/etl_scripts/d_death.sql
v2.8_to_v4.0/sql_etl/scripts/etl_scripts/e_death_cause.sql
v2.8_to_v4.0/sql_etl/scripts/etl_scripts/g_condition.sql
v2.8_to_v4.0/sql_etl/scripts/etl_scripts/l_vitals.sql

these scripts have been tested on one site's data.

adding scripts for new cdm4.0

---

v2.8_to_v4.0/sql_etl/scripts/etl_scripts/g_condition.sql

splitting condition query to handle missing problem list entries

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/g_encounter.sql

Fixes issue #396
extracting the primary payer information

primary prayer implementation

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/g_encounter.sql

fixes #382
Selecting the DRG which qualifies the following:
- MS-DRG,
- qualifier_concept is primary concept

records with multiple DRGs

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/h_diagnosis.sql

fixes #382
Extracting the poa information from the pedsnet data to pcornet.

extracting dx_poa

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/a_person_visit_start2001.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/b_demographic.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/c_enrollment.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/d_death.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/e_death_cause.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/f_provider.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/h_condition.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/h_diagnosis.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/i_procedures.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/j_dispensing.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/l_vitals.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/m_lab_result_cm.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/n_med_admin.sql

fixes #392
revise all etl scripts to use central pcornet map

central pcornet maps

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/m_lab_result_cm.sql

fixes #402
following changes made:
[/] added new query specimen_value, added new field
[/] added the new column specimen_concept_id in lab_measurements
[/] removed entries for measurement_concept_id is null
[/] modified he vocabulary left join to inner join for c1
[/]modified the join for the specimen_source

Modified the lab query

---

v2.9_to_v4.1/sql_etl/data/concept_map.csv
v2.9_to_v4.1/sql_etl/data/concept_map/pedsnet_to_pcornet_doseunit_map.csv
v2.9_to_v4.1/sql_etl/data/concept_map/pedsnet_to_pcornet_rx_frequency_map.csv

POC-284
fixes #414
updating the concept maps to resolve the issue with the values outside
data model specification issue in Data Curation

updating the concept maps

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/j_dispensing.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/o_constraints.sql

fixes #418
Following changes are made:
when the days supply is zero days add those entries to null.
reshuffled the constraints to resolve the slowness in creating FK

updated the dispensing script

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/f_provider.sql

Fixes #416
Provider NPI is now set to null and the flag associated with the same
is set to ’N’ too

updating the provider

---

v2.9_to_v4.1/sql_etl/scripts/etl_scripts/h_condition.sql
v2.9_to_v4.1/sql_etl/scripts/etl_scripts/h_diagnosis.sql

PCO-309
fixes #427
modifying the logic for extracting the condition column

updating condition column

---

v2.7_to_3.1/sql_etl/requirements.txt
v2.8_to_3.1/python_etl/requirements.txt
v2.8_to_3.1/sql_etl/requirements.txt
v2.8_to_v4.0/sql_etl/requirements.txt
v3.0_to_v4.1/sql_etl/requirements.txt

Fixes #440
Removing the flask module in the requirement.txt file as it it not used
and causing the security vulnerability

updating requirement_txt

---

v2.7_to_3.1/sql_etl/requirements.txt
v2.8_to_3.1/sql_etl/requirements.txt
v2.8_to_v4.0/sql_etl/requirements.txt
v2.9_to_v4.1/sql_etl/requirements.txt
v3.0_to_v4.1/sql_etl/requirements.txt

OP-137
fixes #446
upgrading the requests app to 2.20.0

upgrading request version 2.20.2

---

v2.9_to_v4.1/sql_etl/requirements.txt

OP-137
fixes #446
upgrading flask to 0.12.3

upgrading flask 0.12.3

---

v3.1_to_v4.1/sql_etl/scripts/etl_scripts/h_diagnosis.sql

fixes #315 
updating the pdx mapping to remove depreciated value for the pdx

updating the pdx mapping

---

v3.1_to_v4.1/sql_etl/scripts/etl_scripts/g_encounter.sql

fixes #444
OP-176
updating the encounter script for discharge_disp

updating logic for discharge_disp

---

v3.1_to_v4.1/sql_etl/scripts/etl_scripts/k_prescribing.sql

fixes #456
OP-175
updating the ETL script to add the new drug_type_concept_id 581373 data

adding 581373 drug_type_concept_id

---

v3.2_to_v4.1/sql_etl/data/concept_map.csv

adding dx_origin

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/h_immunization.sql

OP-470
fixes #469
adding the ETL for immunization table.

adding the immunization table

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/e_death_cause.sql

OP-476
fixes #473
updating the death_cause code for death_cause_source value.

updating death_cause code

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/j_dispensing.sql

OP-474
fixes #475
adding the new field dispense_source.

dispense_source updates

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/m_lab_result_cm.sql

OP-477
fixes #477
adding code for lab_result_source values.

updating lab_result_source

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/b_private_demographic.sql
v3.4_to_v5.0/sql_etl/scripts/etl_scripts/h_immunization.sql
v3.4_to_v5.0/sql_etl/scripts/etl_scripts/m_lab_result_cm.sql

OP-478
fixes #479
adding the ETL for new private demographic table

adding private_demographic

---

v3.4_to_v5.0/sql_etl/scripts/etl_scripts/b_lds_address_history.sql

OP-479
fixes #481
adding the LDS address history table

adding the table

---

v3.6_to_v5.1/sql_etl/scripts/etl_scripts/l_vitals.sql

refactoring vitals

---

v3.7_to_v5.1/sql_etl/scripts/etl_scripts/j_dispensing.sql
v3.7_to_v5.1/sql_etl/scripts/etl_scripts/k_prescribing.sql
v3.7_to_v5.1/sql_etl/scripts/etl_scripts/n_med_admin.sql

- removing fat emulsion from medication tables

v3.7 Updates

---

v4.6_to_v6.0/sql_etl/data/concept_map.csv

add mapping for 38003886
